---

name: Trunkbased example (Push to master)
on:
  push:

jobs:
  env:
    name: Analyze all environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - run: env
