---

name: Tags Mainline

on:
  # Subject to change
  pull_request:

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    # Subject to change
    if: github.event_name == 'pull_request' && github.ref != 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: '0'
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tag (Dry-Run)
        id: build_tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: Create tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: ${{ steps.build_tag.outputs.new_tag }}-${{ github.sha }}
