---

name: Tags Mainline
on:
  push:
    branches: ["main"]

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Bump version and push tag (Dry-Run)
        id: build_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          dry_run: true
      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.build_tag.outputs.new_tag }}-rc.${{ github.sha }}
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release v${{ steps.build_tag.outputs.new_tag }}-RC
          body: |
            ${{ steps.build_tag.outputs.changelog }}
          draft: false
          prerelease: true
