---

name: Tags MR

on:
  pull_request:

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && env.GITHUB_REF_SLUG == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRERELEASE_SUFFIX: rc
          WITH_V: true
          DRY_RUN: true
