---

name: Trunkbased example (Deploy 2)
on:
  release:
    types: [released]

jobs:
  release-update:
    name: Release update
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Update release name
        uses: meeDamian/github-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          tag: ${{ steps.create_tag.outputs.new_tag }}
          allow_override: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [release-update]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - run: env
      - run: echo deploy
