---

name: Trunkbased example (Deploy 1)
on:
  release:
    types: [created, edited]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - run: env
      - run: echo '${{ github.event.inputs.github_tag }} and ${{ github.event.inputs.docker_tag }} deployment'

  update-release:
    name: Pre-Release creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - run: echo ${{ github.event }}

      # - name: Create or Update release
      #   uses: meeDamian/github-release@master
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ steps.create_tag.outputs.new_tag }}
      #     name: Release v${{ steps.build_tag.outputs.new_tag }}
      #     body: |
      #       ${{ steps.build_tag.outputs.changelog }}
      #     draft: true
      #     prerelease: true
      #     allow_override: true
