---

name: Trunkbased example (Deploy 1)
on:
  release:
    types: [published, prereleased]

jobs:
  release-update:
    name: Release update
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Update release name
        uses: meeDamian/github-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          tag: ${{ steps.get_version.outputs.VERSION }}-rc.${{ github.sha }}
          allow_override: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [release-update]
    steps:
      - run: echo deploy
