---

name: Trunkbased example (Deploy 1)
on:
  release:
    types: [published, prereleased]

jobs:
  release-update:
    name: Release update
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get_version.outputs.VERSION }}
      - name: Update release name
        uses: meeDamian/github-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.create_tag.outputs.new_tag }}
          tag: ${{ steps.get_version.outputs.VERSION }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [release-update]
    steps:
      - run: echo deploy
