---

name: Trunkbased example (Push to master)
on:
  push:
    branches: ["main"]

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Bump version and push tag (Dry-Run)
        id: build_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          dry_run: true
      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.build_tag.outputs.new_tag }}-${{ github.sha }}
      - name: Trigger the deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deployment (Blue Env)
          token: ${{ secrets.GROUP_TOKEN }}
          inputs: >
            {
              "github_tag": "${{ steps.create_tag.outputs.new_tag }}",
              "docker_tag": "${{ steps.create_tag.outputs.new_tag }}"
            }
