---

name: Trunkbased example (Deploy 2)
on:
  release:
    types: [released]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - run: env
      - run: echo deploy
